In [1]:
import numpy as np
import pandas as pd

In [3]:
data=pd.read_csv("Prostate_Cancer.csv")

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 10 columns):
id                   100 non-null int64
diagnosis_result     100 non-null object
radius               100 non-null int64
texture              100 non-null int64
perimeter            100 non-null int64
area                 100 non-null int64
smoothness           100 non-null float64
compactness          100 non-null float64
symmetry             100 non-null float64
fractal_dimension    100 non-null float64
dtypes: float64(4), int64(5), object(1)
memory usage: 7.9+ KB


In [5]:
data.isnull().sum()

id                   0
diagnosis_result     0
radius               0
texture              0
perimeter            0
area                 0
smoothness           0
compactness          0
symmetry             0
fractal_dimension    0
dtype: int64

In [6]:
data["diagnosis_result"].unique()

array(['M', 'B'], dtype=object)

In [11]:
x=data.iloc[:,2:10]
y=data.iloc[:,1:2]

In [40]:
data.head()

id diagnosis_result  radius  texture  perimeter  area  smoothness  \
0   1                M      23       12        151   954       0.143   
1   2                B       9       13        133  1326       0.143   
2   3                M      21       27        130  1203       0.125   
3   4                M      14       16         78   386       0.070   
4   5                M       9       19        135  1297       0.141   

   compactness  symmetry  fractal_dimension  
0        0.278     0.242              0.079  
1        0.079     0.181              0.057  
2        0.160     0.207              0.060  
3        0.284     0.260              0.097  
4        0.133     0.181              0.059

In [12]:
y.head()

diagnosis_result
0                M
1                B
2                M
3                M
4                M

In [13]:
x=data.iloc[:,2:10].values
y=data.iloc[:,1:2].values

In [14]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [16]:
one=OneHotEncoder()
z=one.fit_transform(y[:,0:1]).toarray()
y=np.delete(y,0,axis=1)
y=np.concatenate((z,y),axis=1)

In [17]:
y

array([[0.0, 1.0],
       [1.0, 0.0],
       [0.0, 1.0],
       [0.0, 1.0],
       [0.0, 1.0],
       [1.0, 0.0],
       [0.0, 1.0],
       [0.0, 1.0],
       [0.0, 1.0],
       [0.0, 1.0],
       [0.0, 1.0],
       [0.0, 1.0],
       [1.0, 0.0],
       [0.0, 1.0],
       [0.0, 1.0],
       [0.0, 1.0],
       [0.0, 1.0],
       [0.0, 1.0],
       [0.0, 1.0],
       [1.0, 0.0],
       [1.0, 0.0],
       [1.0, 0.0],
       [0.0, 1.0],
       [0.0, 1.0],
       [0.0, 1.0],
       [0.0, 1.0],
       [0.0, 1.0],
       [0.0, 1.0],
       [0.0, 1.0],
       [0.0, 1.0],
       [0.0, 1.0],
       [0.0, 1.0],
       [0.0, 1.0],
       [0.0, 1.0],
       [0.0, 1.0],
       [0.0, 1.0],
       [0.0, 1.0],
       [1.0, 0.0],
       [0.0, 1.0],
       [0.0, 1.0],
       [0.0, 1.0],
       [0.0, 1.0],
       [0.0, 1.0],
       [0.0, 1.0],
       [0.0, 1.0],
       [0.0, 1.0],
       [1.0, 0.0],
       [0.0, 1.0],
       [1.0, 0.0],
       [1.0, 0.0],
       [1.0, 0.0],
       [1.0, 0.0],
       [1.0,

In [18]:
y.shape

(100, 2)

In [20]:
from sklearn.model_selection import train_test_split

In [21]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [22]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.fit_transform(x_test)

In [23]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [24]:
cat=Sequential()

In [25]:
cat.add(Dense(8,kernel_initializer="random_uniform",activation="relu"))

Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


In [26]:
cat.add(Dense(16,kernel_initializer="random_uniform",activation="relu"))

In [27]:
cat.add(Dense(2,kernel_initializer="random_uniform",activation="softmax"))

In [28]:
cat.compile("adam","categorical_crossentropy",metrics=["accuracy"])

In [34]:
cat.fit(x_train,y_train,batch_size=32,epochs=20)

Epoch 1/20
80/80 [==============================] - 0s 364us/sample - loss: 0.2867 - acc: 0.8625
Epoch 2/20
80/80 [==============================] - 0s 263us/sample - loss: 0.2864 - acc: 0.8625
Epoch 3/20
80/80 [==============================] - 0s 275us/sample - loss: 0.2858 - acc: 0.8625
Epoch 4/20
80/80 [==============================] - 0s 226us/sample - loss: 0.2859 - acc: 0.8500
Epoch 5/20
80/80 [==============================] - 0s 288us/sample - loss: 0.2850 - acc: 0.8750
Epoch 6/20
80/80 [==============================] - 0s 112us/sample - loss: 0.2846 - acc: 0.8750
Epoch 7/20
80/80 [==============================] - 0s 188us/sample - loss: 0.2842 - acc: 0.8750
Epoch 8/20
80/80 [==============================] - 0s 157us/sample - loss: 0.2839 - acc: 0.8750
Epoch 9/20
80/80 [==============================] - 0s 138us/sample - loss: 0.2833 - acc: 0.8750
Epoch 10/20
80/80 [==============================] - 0s 188us/sample - loss: 0.2828 - acc: 0.8750
Epoch 11/20
80/80 [==========

In [36]:
ypred=cat.predict(x_test)

In [37]:
ypred

array([[0.39423144, 0.60576856],
       [0.8387843 , 0.16121565],
       [0.06098535, 0.9390146 ],
       [0.9923373 , 0.00766268],
       [0.46315965, 0.5368403 ],
       [0.8585758 , 0.14142412],
       [0.7047577 , 0.29524234],
       [0.9190444 , 0.08095558],
       [0.81386834, 0.1861316 ],
       [0.01649581, 0.9835042 ],
       [0.17700925, 0.8229907 ],
       [0.9115775 , 0.08842249],
       [0.03938117, 0.96061885],
       [0.09250034, 0.9074996 ],
       [0.67949533, 0.32050467],
       [0.06739827, 0.93260175],
       [0.09590621, 0.9040938 ],
       [0.18485288, 0.8151471 ],
       [0.02557301, 0.974427  ],
       [0.4329158 , 0.5670842 ]], dtype=float32)

In [38]:
y_test

array([[0.0, 1.0],
       [0.0, 1.0],
       [0.0, 1.0],
       [1.0, 0.0],
       [0.0, 1.0],
       [1.0, 0.0],
       [0.0, 1.0],
       [0.0, 1.0],
       [0.0, 1.0],
       [0.0, 1.0],
       [0.0, 1.0],
       [1.0, 0.0],
       [0.0, 1.0],
       [0.0, 1.0],
       [0.0, 1.0],
       [0.0, 1.0],
       [0.0, 1.0],
       [0.0, 1.0],
       [0.0, 1.0],
       [0.0, 1.0]], dtype=object)

In [41]:
cat.predict_classes(sc.transform([[23,12,151,954,0.143,0.278,0.242,0.079]]))

array([1], dtype=int64)

In [43]:
cat.predict_classes(sc.transform([[9,9,183,2326,0.343,0.062,0.191,0.027]]))

array([1], dtype=int64)

In [46]:
cat.predict_classes(sc.transform([[25,25,83,477,0.128,0.170,0.209,0.076]]))

array([0], dtype=int64)

In [47]:
yp=cat.predict(sc.transform([[25,25,83,477,0.128,0.170,0.209,0.076]]))

In [48]:
yp>0.5

array([[ True, False]])

In [49]:
yp

array([[0.84691614, 0.15308382]], dtype=float32)