In [1]:
import numpy as np
import pandas as pd

In [2]:
dataset=pd.read_csv("Bank_Personal_Loan_Modelling.csv")

In [3]:
dataset.head()

ID  Age  Experience  Income  ZIP Code  Family  CCAvg  Education  Mortgage  \
0   1   25           1      49     91107       4    1.6          1         0   
1   2   45          19      34     90089       3    1.5          1         0   
2   3   39          15      11     94720       1    1.0          1         0   
3   4   35           9     100     94112       1    2.7          2         0   
4   5   35           8      45     91330       4    1.0          2         0   

   Personal Loan  Securities Account  CD Account  Online  CreditCard  
0              0                   1           0       0           0  
1              0                   1           0       0           0  
2              0                   0           0       0           0  
3              0                   0           0       0           0  
4              0                   0           0       0           1

In [4]:
dataset.isnull().any()

ID                    False
Age                   False
Experience            False
Income                False
ZIP Code              False
Family                False
CCAvg                 False
Education             False
Mortgage              False
Personal Loan         False
Securities Account    False
CD Account            False
Online                False
CreditCard            False
dtype: bool

In [11]:
x=dataset.iloc[:,1:13].values
y=dataset.iloc[:,13].values

In [12]:
y

array([0, 0, 0, ..., 0, 0, 1], dtype=int64)

In [13]:
x

array([[25.,  1., 49., ...,  1.,  0.,  0.],
       [45., 19., 34., ...,  1.,  0.,  0.],
       [39., 15., 11., ...,  0.,  0.,  0.],
       ...,
       [63., 39., 24., ...,  0.,  0.,  0.],
       [65., 40., 49., ...,  0.,  0.,  1.],
       [28.,  4., 83., ...,  0.,  0.,  1.]])

In [14]:
x.shape

(5000, 12)

In [18]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test= train_test_split(x,y,test_size=0.2,random_state=0)

In [19]:
from sklearn.preprocessing import StandardScaler
sc =StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

In [20]:
from tensorflow.keras.models import Sequential #-used to initialize the model.
from tensorflow.keras.layers import Dense #- used to add layers of ANN

In [26]:
b= Sequential()

In [27]:
b.add(Dense(12,kernel_initializer="random_uniform",activation='relu'))

In [28]:
b.add(Dense(24,kernel_initializer="random_uniform",activation='relu'))

In [29]:
b.add(Dense(1,kernel_initializer="random_uniform",activation='sigmoid'))

In [30]:
b.compile("adam","binary_crossentropy", metrics= ["accuracy"])

In [35]:
b.fit(x_train,y_train,batch_size=32,epochs =150)

Epoch 1/150
4000/4000 [==============================] - 0s 72us/sample - loss: 0.5220 - acc: 0.7475
Epoch 2/150
4000/4000 [==============================] - 0s 70us/sample - loss: 0.5213 - acc: 0.7455
Epoch 3/150
4000/4000 [==============================] - 0s 78us/sample - loss: 0.5224 - acc: 0.7465
Epoch 4/150
4000/4000 [==============================] - 0s 67us/sample - loss: 0.5216 - acc: 0.7465
Epoch 5/150
4000/4000 [==============================] - 0s 75us/sample - loss: 0.5216 - acc: 0.7470
Epoch 6/150
4000/4000 [==============================] - 0s 65us/sample - loss: 0.5212 - acc: 0.7450
Epoch 7/150
4000/4000 [==============================] - 0s 74us/sample - loss: 0.5209 - acc: 0.7445
Epoch 8/150
4000/4000 [==============================] - 0s 72us/sample - loss: 0.5212 - acc: 0.7450
Epoch 9/150
4000/4000 [==============================] - 0s 76us/sample - loss: 0.5216 - acc: 0.7465
Epoch 10/150
4000/4000 [==============================] - 0s 65us/sample - loss: 0.5209 - a

4000/4000 [==============================] - 0s 64us/sample - loss: 0.5172 - acc: 0.7483
Epoch 82/150
4000/4000 [==============================] - 0s 65us/sample - loss: 0.5168 - acc: 0.7483
Epoch 83/150
4000/4000 [==============================] - 0s 64us/sample - loss: 0.5164 - acc: 0.7485
Epoch 84/150
4000/4000 [==============================] - 0s 61us/sample - loss: 0.5163 - acc: 0.7452
Epoch 85/150
4000/4000 [==============================] - 0s 64us/sample - loss: 0.5172 - acc: 0.7473
Epoch 86/150
4000/4000 [==============================] - 0s 63us/sample - loss: 0.5154 - acc: 0.7473
Epoch 87/150
4000/4000 [==============================] - 0s 63us/sample - loss: 0.5169 - acc: 0.7485
Epoch 88/150
4000/4000 [==============================] - 0s 64us/sample - loss: 0.5175 - acc: 0.7458
Epoch 89/150
4000/4000 [==============================] - 0s 65us/sample - loss: 0.5170 - acc: 0.7462
Epoch 90/150
4000/4000 [==============================] - 0s 64us/sample - loss: 0.5157 - acc: 

In [48]:
ypred=b.predict(x_test)

In [49]:
ypred

array([[3.5698646e-01],
       [2.7491379e-01],
       [2.4957761e-01],
       [2.9134768e-01],
       [2.5935149e-01],
       [2.0091444e-01],
       [1.9592011e-01],
       [9.5066708e-01],
       [6.0439503e-01],
       [1.8124217e-01],
       [1.3911545e-01],
       [2.6579431e-01],
       [3.2162678e-01],
       [2.2018257e-01],
       [2.7602565e-01],
       [2.9400757e-01],
       [3.7203962e-01],
       [2.3050439e-01],
       [3.0719396e-01],
       [2.0736444e-01],
       [1.0730624e-03],
       [2.3746431e-02],
       [9.6142769e-01],
       [2.9304922e-03],
       [4.9690285e-01],
       [2.1523470e-01],
       [8.9175355e-01],
       [3.3004668e-01],
       [3.4899947e-01],
       [7.6735914e-02],
       [2.5645021e-01],
       [2.3836899e-01],
       [2.9392791e-01],
       [3.7137905e-01],
       [3.1663856e-01],
       [2.8221920e-01],
       [3.0935180e-01],
       [3.6894318e-01],
       [3.8345978e-01],
       [2.1171039e-01],
       [2.2206202e-01],
       [2.242764

In [38]:
ypred = ypred>0.5

In [39]:
ypred

array([[False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [

In [40]:
y_test

array([0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0,

In [41]:
dataset.head()

ID  Age  Experience  Income  ZIP Code  Family  CCAvg  Education  Mortgage  \
0   1   25           1      49     91107       4    1.6          1         0   
1   2   45          19      34     90089       3    1.5          1         0   
2   3   39          15      11     94720       1    1.0          1         0   
3   4   35           9     100     94112       1    2.7          2         0   
4   5   35           8      45     91330       4    1.0          2         0   

   Personal Loan  Securities Account  CD Account  Online  CreditCard  
0              0                   1           0       0           0  
1              0                   1           0       0           0  
2              0                   0           0       0           0  
3              0                   0           0       0           0  
4              0                   0           0       0           1

In [46]:
yp=b.predict(sc.transform([[25,1,49,91107,4,1.6,1,0,0,1,0,0]]))

In [47]:
yp

array([[0.13652539]], dtype=float32)

In [50]:
yp>0.5

array([[False]])